import os
from dotenv import load_dotenv

load_dotenv()

# ==========================================
# CONFIGURABLE ENVIRONMENT VARIABLES
# ==========================================

DEFAULT_REGISTRATION_PORT_RETRY_TIME = float(os.getenv("DEFAULT_REGISTRATION_PORT_RETRY_TIME", "0.01"))
DEFAULT_MESSAGE_TIMEOUT_TIME = int(os.getenv("DEFAULT_MESSAGE_TIMEOUT_TIME", "5"))
DEFAULT_TCP_BACKLOG = int(os.getenv("DEFAULT_TCP_BACKLOG", "10"))
SERVER_STARTING_TIME = float(os.getenv("SERVER_STARTING_TIME", "0.5"))

_port_start = int(os.getenv("AVAILABLE_PORTS_START", "4003"))
_port_end = int(os.getenv("AVAILABLE_PORTS_END", "4100"))
AVAILABLEPORTS = range(_port_start, _port_end+1)
# AVAILABLEPORTS = range(4003, 4100)

DEFAULT_EMA_LAUNCH_ABILITY_ACTIVE = int(os.getenv("DEFAULT_EMA_LAUNCH_ABILITY_ACTIVE", "1"))==1
DEFAULT_EMA_REGISTER_PORT = int(os.getenv("DEFAULT_EMA_REGISTER_PORT", "4001"))
DEFAULT_EMA_HEARTBEAT_INTERVAL = int(os.getenv("DEFAULT_EMA_HEARTBEAT_INTERVAL", "5000"))
DEFAULT_EMA_MESSAGE_RETRYS = int(os.getenv("DEFAULT_EMA_MESSAGE_RETRYS", "3"))
DEFAULT_EMA_MESSAGE_RETRY_INTERVAL = float(os.getenv("DEFAULT_EMA_MESSAGE_RETRY_INTERVAL", "0.5"))
DEFAULT_EMA_HEARTBEAT_FAILURE_THRESHOLD = int(os.getenv("DEFAULT_EMA_HEARTBEAT_FAILURE_THRESHOLD", "5"))
DEFAULT_AGENT_HEARTBEAT_FAILURE_THRESHOLD = int(os.getenv("DEFAULT_AGENT_HEARTBEAT_FAILURE_THRESHOLD", "5"))
DEFAULT_AGENT_STILL_ALIVE_THRESHOLD = int(os.getenv("DEFAULT_AGENT_STILL_ALIVE_THRESHOLD", "1"))
DEFAULT_EMA_EXTERNAL_HEARTBEAT_TIMEOUT = float(os.getenv("DEFAULT_EMA_EXTERNAL_HEARTBEAT_TIMEOUT", "0.5"))

DEFAULT_MULTICAST_IP = os.getenv("DEFAULT_MULTICAST_IP", "224.1.1.1")
DEFAULT_MULTICAST_PORT = int(os.getenv("DEFAULT_MULTICAST_PORT", "4002"))

DEFAULT_CONTRACTNETINITIATOR_RECEIVE_CFPS_TIMEOUT = float(os.getenv("DEFAULT_CONTRACTNETINITIATOR_RECEIVE_CFPS_TIMEOUT", "5")) 

# ==========================================
# INTERNAL SYSTEM CONSTANTS
# ==========================================

LOCALHOST = "127.0.0.1"
ALL_INTERFACES = "0.0.0.0"
DEFAULT_EMA_PORT = 4000
DEFAULT_UDP_PACKETSIZE = 65535
DEFAULT_KERNEL_STABILIZATION_TIME = 0.005
DEFAULT_LOOP_STABILIZATION_TIME = 0.005
DEFAULT_EMA_NAME = "EMA"
DEFAULT = "DEFAULT"
DEFAULT_THREAD_JOIN_TIMEOUT_TIME = 2
DEFAULT_AGENT_ALREADY_EXISTS = -1
DEFAULT_EMA_HAS_NO_MORE_PORTS = -2
DEFAULT_OUTSIDE_AGENT = -3

# Ontologies and Actions
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_AGENTADDRESS_CONCEPT = "am-agent-address"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_INFORM_CONCEPT = "am-inform"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_AGENTDESCRIPTION_CONCEPT = "am-agent-description"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_NAME = "tamaf-agent-management"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_REGISTER_ACTION = "register"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_REGISTER_RESULT_ACTION = "register-result"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_DEREGISTER_ACTION = "deregister"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_DEREGISTER_RESULT_ACTION = "deregister-result"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_MODIFY_ACTION = "modify"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_MODIFY_RESULT_ACTION = "modify-result"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_LOCAL_SEARCH_ACTION = "local-search"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_EXTERNAL_SEARCH_ACTION = "external-search"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_GLOBAL_SEARCH_ACTION = "global-search"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_SEARCH_RESULT_ACTION = "search-result"
DEFAULT_AGENTMANAGEMENT_ONTOLOGY_KEEPALIVE_ACTION = "keepalive"
DEFAULT_ENVIRONMENTMANAGEMENT_ONTOLOGY_ENVIRONMENTUDPATE_CONCEPT = "ema-environment-lastupdatetime"
DEFAULT_ENVIRONMENTMANAGEMENT_ONTOLOGY_NAME = "tamaf-environment-management"
DEFAULT_ENVIRONMENTMANAGEMENT_ONTOLOGY_SEARCH_ACTION = "search"
DEFAULT_ENVIRONMENTMANAGEMENT_ONTOLOGY_KEEPALIVE_ACTION = "keepalive"

MULTICAST_ADDRESS = (DEFAULT_MULTICAST_IP, DEFAULT_MULTICAST_PORT)

# ==========================================
# EXCEPTIONS
# ==========================================
class EmptyReceiveException(Exception):
    pass

class EMAFailureException(Exception):
    pass

class AgentAlreadyExistsException(Exception):
    pass

class EMANoMorePortsException(Exception):
    pass