[platformio]
default_envs = esp32dev
src_dir = .
extra_configs = secrets.ini

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_deps =
    bblanchon/ArduinoJson@^7.0.0

lib_extra_dirs =
    ../../../mk3/esp32package

build_unflags =
    -std=gnu++11
    -fno-exceptions

build_flags =
    -std=gnu++17
    -fexceptions
    -I../../../mk3/esp32package/src
    -D AGENT_MODE=3
    -D WIFI_SSID=\"${secrets.wifi_ssid}\"
    -D WIFI_PASSWORD=\"${secrets.wifi_pass}\"
    -D EMA_IP=\"${secrets.ema_ip}\"
