#ifndef TAMAF_DEFINES_H
#define TAMAF_DEFINES_H

#define DEFAULT_REGISTRATION_PORT_RETRY_TIME 0.5
#define DEFAULT_MESSAGE_TIMEOUT_TIME 5
#define DEFAULT_TCP_BACKLOG 10
#define SERVER_STARTING_TIME 0.5

#define DEFAULT_EMA_LAUNCH_ABILITY_ACTIVE 1
#define DEFAULT_EMA_REGISTER_PORT 4001
#define DEFAULT_EMA_HEARTBEAT_INTERVAL 5000
#define DEFAULT_EMA_MESSAGE_RETRYS 3
#define DEFAULT_EMA_MESSAGE_RETRY_INTERVAL 0.5
#define DEFAULT_EMA_HEARTBEAT_FAILURE_THRESHOLD 5
#define DEFAULT_AGENT_HEARTBEAT_FAILURE_THRESHOLD 5
#define DEFAULT_EMA_EXTERNAL_HEARTBEAT_TIMEOUT 0.5
#define DEFAULT_AGENT_STILL_ALIVE_THRESHOLD 1
#define DEFAULT_AGENT_ALREADY_EXISTS -1

#define DEFAULT_MULTICAST_IP "224.1.1.1"
#define DEFAULT_MULTICAST_PORT 4002

#define LOCALHOST "127.0.0.1"
#define ALL_INTERFACES "0.0.0.0"
#define DEFAULT_EMA_PORT 4000
#define DEFAULT_UDP_PACKETSIZE 65535
#define DEFAULT_KERNEL_STABILIZATION_TIME_S 0.1
#define DEFAULT_KERNEL_STABILIZATION_TIME_MS 100
#define DEFAULT_LOOP_STABILIZATION_TIME_S 0.1
#define DEFAULT_LOOP_STABILIZATION_TIME_MS 100
#define DEFAULT_EMA_NAME "EMA"
#define DEFAULT_THREAD_JOIN_TIMEOUT_TIME 2

// Ontologies and Actions
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_NAME "tamaf-agent-management"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_AGENTPORT_CONCEPT "am-agent-port"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_INFORM_CONCEPT "am-inform"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_AGENTDESCRIPTION_CONCEPT "am-agent-description"

#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_REGISTER_ACTION "register"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_REGISTER_RESULT_ACTION "register-result"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_DEREGISTER_ACTION "deregister"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_DEREGISTER_RESULT_ACTION "deregister-result"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_MODIFY_ACTION "modify"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_MODIFY_RESULT_ACTION "modify-result"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_LOCAL_SEARCH_ACTION "local-search"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_EXTERNAL_SEARCH_ACTION "external-search"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_GLOBAL_SEARCH_ACTION "global-search"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_SEARCH_RESULT_ACTION "search-result"
#define DEFAULT_AGENTMANAGEMENT_ONTOLOGY_KEEPALIVE_ACTION "keepalive"

#define DEFAULT_ENVIRONMENTMANAGEMENT_ONTOLOGY_NAME "tamaf-environment-management"
#define DEFAULT_ENVIRONMENTMANAGEMENT_ONTOLOGY_ENVIRONMENTUDPATE_CONCEPT "ema-environment-lastupdatetime"
#define DEFAULT_ENVIRONMENTMANAGEMENT_ONTOLOGY_SEARCH_ACTION "search"
#define DEFAULT_ENVIRONMENTMANAGEMENT_ONTOLOGY_KEEPALIVE_ACTION "keepalive"

#endif // TAMAF_DEFINES_H
