#ifndef TAMAF_LIFECYCLESTATE_H
#define TAMAF_LIFECYCLESTATE_H

typedef enum {
    TAMAF_STATE_INITIATED,
    TAMAF_STATE_ACTIVE,
    TAMAF_STATE_SUSPENDED,
    TAMAF_STATE_WAITING,
    TAMAF_STATE_DELETED,
    TAMAF_STATE_TRANSIT,
    TAMAF_STATE_CLOSING
} tamaf_lifecyclestate_t;

#endif // TAMAF_LIFECYCLESTATE_H
