name=TAMAF-ESP32
version=1.0.0
author=Raul JMD
maintainer=Raul JMD
sentence=Tiny Agent Management Architecture Framework for ESP32.
paragraph=A highly optimized C++ implementation of the TAMAF multi-agent system framework, designed to run cooperatively on FreeRTOS for the ESP32. Implements FIPA standard ACL messages, ContractNet and Request protocols.
category=Communication
url=https://github.com/RaulJMD/Master-Thesis
architectures=esp32
depends=ArduinoJson
